
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgjrzmttcpuyyvosxdun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnanJ6bXR0Y3B1eXl2b3N4ZHVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4OTY5NzMsImV4cCI6MjA2MjQ3Mjk3M30.fot3WHSrYNOVjBOxzMW8O6raJSta0VE6wb9QIZK9GZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
